config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 
resources :invoices do
  collection do
    get 'pending' 
    get 'collection' 
  end
end


  root 'invoices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
	def index
		@invoices = Invoice.all	
	end

	def new
		@invoice = Invoice.new
	end

	def create
	  @invoice = Invoice.new(invoice_params)

	  if @invoice.save
	  	redirect_to @invoice
	  else
	  	render 'new'
	   end
	end

	def edit
  		@invoice = Invoice.find(params[:id])
	end

	def show
		@invoice = Invoice.find(params[:id])
	end

	def update
		@invoice = Invoice.find(params[:id])

		 if @invoice.update(invoice_params)
		   redirect_to @invoice
		 else
		 	render 'edit'
		 end
    end

   	

    
    
private
	def invoice_params 
		params.require(:invoice).permit(:reference, :invoice_date, :customer, :brandmanager, :narration, :amount, :totalcollection, :newcollection, :sumcollection, :balance_due)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@product = Product.all
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to @product
		else
		  render 'new'
		end
	end

app/helpers/application_helper.rb
module ApplicationHelper

	def invoices(&block)
  		content_tag(:table, block.call, id: 'table')
  	end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/invoices/edit.html.erb
				<%= simple_form_for @invoice do |f| %>  =
           <%= f.input :reference %>
           <%= f.input :invoice_date %>
           <%= f.input :customer %>
           <%= f.input :brandmanager %>  
           <%= f.input :narration %>
           <%= f.input :amount %> 
           <%= f.input :totalcollection %>
           <%= f.button :button, " submit", class: "btn-primary" %>
     			</form>
		<% end %>
		

 

app/views/invoices/index.html.erb
<%= link_to '<button type="button" class="btn btn-primary">Add new bill</button>'.html_safe,new_invoice_path %>
<button type="button" class="btn btn-primary" onclick="myFunction2()">Show pending bills</button>
<button type="button" class="btn btn-primary" onclick="myFunction()"> Show collected bills </button>
<table class = table>
	<thead>
      <tr>
        <th>References</th>
        <th>Invoice Date</th>
        <th>Customer</th>
        <th>brandmaster</th>
        <th>Narration</th>
        <th>Amount</th>
        <th>Total collection</th>
        <th>Balance due</th>
      </tr>
    </thead>
  <% @invoices.each do |invoice| %>
    <tbody>
    <tr>
          <td><%= link_to invoice.reference, invoice_path(invoice) %></td>
           <td><%= invoice.invoice_date %></td> 
           <td><%= invoice.customer %></td> 
           <td><%= invoice.brandmanager %></td>  
           <td><%= invoice.narration %> </td>
           <td><%= invoice.amount %> </td>
           <td><%= invoice.totalcollection %> </td>
           <td><%=  invoice.balance_due = invoice.amount - invoice.totalcollection   %> </td>
           <td><%= link_to'<button type="button" class="btn btn-primary"> Add collection</button>'.html_safe,edit_invoice_path(invoice) %> </td>                  
    </tr>
    </tbody>
  <% end %>
</table>

<div id ="collected">
<table class = table> 
  <thead>
      <tr>
        <th>References</th>
        <th>Invoice Date</th>
        <th>Customer</th>
        <th>brandmaster</th>
        <th>Narration</th>
        <th>Amount</th>
        <th>Total collection</th>
        <th>Balance due</th>
      </tr>
    </thead>
  <% @invoices.each do |invoice| %>
 <% if invoice.balance_due == 0  %>
    <tbody>
    <tr>
          <td><%= link_to invoice.reference , invoice_path(invoice) %></td>
           <td><%= invoice.invoice_date %></td> 
           <td><%= invoice.customer %></td> 
           <td><%= invoice.brandmanager %></td>  
           <td><%= invoice.narration %> </td>
           <td><%= invoice.amount %> </td>
           <td><%= invoice.totalcollection %> </td>
           <td><%= invoice.balance_due %> </td>
           <td><%= link_to'<button type="button" class="btn btn-primary"> Add collection</button>'.html_safe,new_invoice_path %> </td>               
    </tr>
    </tbody>
  <% end %>
    <% end %>
</table>
</div>

<div id ="pending">
<table class = table>
  <thead>
      <tr>
        <th>References</th>
        <th>Invoice Date</th>
        <th>Customer</th>
        <th>brandmaster</th>
        <th>Narration</th>
        <th>Amount</th>
        <th>Total collection</th>
        <th>Balance due</th>
      </tr>
    </thead>
  <% @invoices.each do |invoice| %>
 <% if invoice.balance_due > 0  %>
    <tbody>
    <tr>
          <td><%= link_to invoice.reference , invoice_path(invoice) %></td>
           <td><%= invoice.invoice_date %></td> 
           <td><%= invoice.customer %></td> 
           <td><%= invoice.brandmanager %></td>  
           <td><%= invoice.narration %> </td>
           <td><%= invoice.amount %> </td>
           <td><%= invoice.totalcollection %> </td>
           <td><%= invoice.balance_due %> </td>
           <td><%= link_to'<button type="button" class="btn btn-primary"> Add collection</button>'.html_safe,new_invoice_path %> </td>
                   
    </tr>
    </tbody>
  <% end %>
    <% end %>
</table>
</div>

<script>
function myFunction() {
  var x = document.getElementById("collected");
  if (x.style.display == "none") {
    x.style.display = "block";
  } 
  else {
    x.style.display = "none";
  }
}
</script>

<script>
function myFunction2() {
  var x = document.getElementById("pending");
  if (x.style.display == "none") {
    x.style.display = "block";
  } 
  else {
    x.style.display = "none";
  }
}
</script>

app/views/invoices/new.html.erb
<div class="col-md-6 col-md-offset-3">
<div class="new-book-form">
				<%= simple_form_for @invoice do |f| %>  =
           <%= f.input :reference %>
           <%= f.input :invoice_date %>
           <%= f.input :customer %>
           <%= f.input :brandmanager %>  
           <%= f.input :narration %>
           <%= f.input :amount %> 
           <%= f.input :totalcollection %> 
           <%= f.button :button, " submit", class: "btn-primary" %>
     			</form>
		<% end %>
</div>
		

 

app/views/invoices/show.html.erb
<p>
  <%= @invoice.reference %>
</p>
 
<p>
  <%= @invoice.customer %>
</p>

<p>
  <%= @invoice.brandmanager %>
</p>

<p>

  <%= @invoice.narration %>
</p>
 
<table class ="table">
 <thead>
      <tr>
        <th>Date</th>
        <th>Event</th>
        <th>Amount</th>
     </tr>
 </thead>
 <tbody>
    <tr>
    <td><%= @invoice.invoice_date %> </td>
    <td> New Invoice </td>
    <td> <%= @invoice.amount %> </td>
    </tr>

    <tr>
    <td><%= @invoice.invoice_date %> </td>
    <td> NewCollection </td>
    <td> <%= @invoice.totalcollection %>
    </tr>
     <tr>
    <td> </td>
    <td> Balance </td>
    <td> <%= @invoice.balance_due = @invoice.amount - @invoice.totalcollection %> </td>
    </tr>
    
</tbody>
</table>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Account</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>